name: test-go-code
on:
  push:
    - branches:
      - master
      - 'release/**'
  pull_request:
    - branches:
      - master
jobs:
  test:
    runs-on: ubuntu-20.04
  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.5'

    - name: Install dependencies
      run: go mod tidy -v

    - name: Build go binary
      run: go build -v ./...
    
    - name: Test go code
      run: go test -v ./...
